const ACTION = {
  SET_INDICATOR: 'SET_INDICATOR',
  SET_NODE: 'SET_NODE',
  SET_CONNECTOR: 'SET_CONNECTOR',
  SET_NEW_CONNECTOR: 'SET_NEW_CONNECTOR',
  SET_CONNECTION_POINT: 'SET_CONNECTION_POINT',

  SET_INDICATOR_EDIT: 'SET_INDICATOR_EDIT',
  SET_NODE_EDIT: 'SET_NODE_EDIT',

  ADD_CONNECTOR: 'ADD_CONNECTOR',
  ADD_INDICATOR: 'ADD_INDICATOR',
  ADD_NODE: 'ADD_NODE',

  DELETE_INDICATOR: 'DELETE_INDICATOR',
  DELETE_NODE: 'DELETE_NODE',
  DELETE_CONNECTOR: 'DELETE_CONNECTOR',

  UPDATE_NODE_PROPERTIES: 'UPDATE_NODE_PROPERTIES',
  UPDATE_SHAPE_TEXT: 'UPDATE_SHAPE_TEXT',

  CLEAR_DIAGRAM: 'CLEAR_DIAGRAM',
  IMPORT: 'IMPORT',

  GRID_VIEW: 'GRID_VIEW',
  GRID_SNAP: 'GRID_SNAP',
  UNDO: 'UNDO',
  REDO: 'REDO',
  AUTO_LAYOUT: 'AUTO_LAYOUT',

  ESCAPE: 'ESCAPE',
  CHANGE_SCALE: 'CHANGE_SCALE',
};

export default ACTION;
